#!/usr/bin/env bash
echo "Running checkstyle check..."
OUTPUT="/tmp/checkstyle-$(date +%s)"
./gradlew check > $OUTPUT
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  cat $OUTPUT
  rm $OUTPUT
  echo "***********************************************"
  echo "                 Checkstyle failed                 "
  echo " Please fix the above issues before committing "
  echo "***********************************************"
  exit $EXIT_CODE
fi
rm $OUTPUT